#########################
#      main config      #
#########################
#Suspect level decrease rate
#嫌疑等级减少速度
#Decrease per gt
#每游戏刻减少量
Main.SuspicionLevel.DecreaseRate: 1
Main.Mode: "kick"


#Maximum allowable suspicion level
#最大允许嫌疑等级
Main.SuspicionLevel.Max: 5000


#Event backtracking Level
#事件回溯等级
Main.SuspicionLevel.Backtracking: 2500



######################
#      movement      #
######################
#"CheckSpeed" will determine if the player is speeding according to the preset
#"CheckSpeed"将会按照预设判断玩家是否超速
DetectionItem.Drop.CheckSpeed: true


#"MaxSpeed" will run separately from the preset, but the master switch will remain "CheckSpeed"
#"MaxSpeed"将与预设分开运行,但总开关仍是"CheckSpeed"
DetectionItem.Drop.MaxSpeed: 4.0

DetectionItem.Drop.SuspicionLevel: 100


#HighJump
#高跳
DetectionItem.Jump.CheckHeight: true
#Maximum allowable jump height
#最大允许跳跃高度
DetectionItem.Jump.MaxHeight: 130

DetectionItem.Jump.SuspicionLevel: 500


#Flight
#飞行
DetectionItem.Flight.CheckHorizontalFlight: true
DetectionItem.Flight.CheckFastFlight: true


#Flexible
#空中灵活运动
DetectionItem.Flight.CheckFlexibleFlight: true

DetectionItem.Flight.SuspicionLevel: 100


#SafeWalk
#安全行走
DetectionItem.Walk.CheckSafeWalk: true


#LiquidWalk
#水上漂
DetectionItem.Walk.CheckLiquidWalk: true

DetectionItem.Walk.SuspicionLevel: 100


#WallClimb
#爬墙
DetectionItem.Climb.CheckWallClimb: true
DetectionItem.Climb.FastClimb: true

DetectionItem.Climb.SuspicionLevel: 100


#WaterSpeed
#水中疾行
DetectionItem.Swim.CheckWaterSpeed: true

DetectionItem.Swim.SuspicionLevel: 75


#Timer
#变速齿轮
DetectionItem.Time.CheckTimer: true
DetectionItem.Time.MaxPacket: 20

DetectionItem.Time.SuspicionLevel: 30



####################
#      combat      #
####################
#Criticals
#刀刀暴击
DetectionItem.Combat.CheckCritical: true
DetectionItem.Combat.Critical.SuspicionLevel: 100


#Reach
#长臂猿
DetectionItem.Combat.CheckReach: true
DetectionItem.Combat.Reach: 3.39

DetectionItem.Combat.Reach.SuspicionLevel: 100


#CPS
#攻击速度
DetectionItem.Combat.CPS.CheckCPS: true
DetectionItem.Combat.CPS.MaxCPS: 18

DetectionItem.Combat.CPS.SuspicionLevel: 100

#KillAura
#杀戮光环
DetectionItem.Combat.KillAura.Simple: true

DetectionItem.Combat.KillAura.SuspicionLevel: 300