name: HNC-RL
main: com.github.hsn8086.Main
version: 0.1.6-SNAPSHOT-build1
author: hsn
description: A Minecraft server anti-cheat.
depend: [ Kotlin ]

commands:
  
  hnc_reload:
    description: hnc_reload
    usage: /<command>

  hnc_debug:
    description: hnc_debug
    usage: /<command>